name: Tutorial Workflow

on: [push]

jobs:
  job1:
    name: Setup Job
    runs-on: ubuntu-latest
    steps:
      - name: Print today's date
        run: echo "Today's date is $(date)"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Check Python version
        run: python --version

      - name: Check pip version
        run: pip --version

  job2:
    name: Secondary Job
    runs-on: ubuntu-latest
    steps:
      - name: Echo Job 2 Date
        run: echo "Job 2 - Date: $(date)"

  job4:
    name: Final Dependent Job
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - name: Print Job 4 Message
        run: echo "I am job 4"
